version: '3.8'
services:
  api:
    build: .
    ports:
      - "8085:8085"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    command: bash scripts/start.sh

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    command: bash scripts/run_tests.sh
    depends_on:
      - api

  test-standalone:
    build: .
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    command: bash scripts/test_only.sh

  test-db-connection:
    build: .
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8085
    command: python3 scripts/test_db_connection.py